name: Build on macos-latest

on:
  workflow_dispatch:  # Manual trigger
  workflow_call:

env:
  SDK_VERSION: "0"

jobs:
  build-toolchain:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Get macos sdk version
      shell: bash
      run: |
        echo "SDK_VERSION=$(xcrun --show-sdk-version)" >> $GITHUB_ENV

    - name: Mkdir /opt/ttmlir-toolchain
      shell: bash
      run: |
        sudo mkdir -p /opt/ttmlir-toolchain
        sudo chown -R ${USER} /opt/ttmlir-toolchain

    - name: 'Cache ttmlir-toolchain'
      id: cache-toolchain
      env:
        SDK_VERSION: ${{ env.SDK_VERSION }}
      uses: actions/cache@v4
      with:
        path: /opt/ttmlir-toolchain
        key: macos-latest-ttmlir-toolchain-${{ hashFiles('env/**') }}-${{ env.SDK_VERSION }}

    - name: 'Build ttmlir-toolchain'
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake -B env/build env
        cmake --build env/build

    - name: Tar ttmlir-toolchain
      shell: bash
      run: |
        tar -czf ttmlir-toolchain-macos-latest.tar.gz -C /opt/ttmlir-toolchain .

    - name: Upload ttmlir-toolchain
      uses: actions/upload-artifact@v4
      with:
        name: ttmlir-toolchain-macos-latest
        path: ttmlir-toolchain-macos-latest.tar.gz

  build:
    needs: build-toolchain
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 # Fetch all history and tags

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Get macos sdk version
      shell: bash
      run: |
        echo "SDK_VERSION=$(xcrun --show-sdk-version)" >> $GITHUB_ENV

    - name: Download ttmlir-toolchain
      uses: actions/download-artifact@v4
      with:
        name: ttmlir-toolchain-macos-latest
        path: .

    - name: Extract ttmlir-toolchain
      shell: bash
      run: |
        sudo mkdir -p /opt/ttmlir-toolchain
        sudo chown -R ${USER} /opt/ttmlir-toolchain
        tar -xzf ttmlir-toolchain-macos-latest.tar.gz -C /opt/ttmlir-toolchain

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        key: macos-latest-runtime-OFF-${{ env.SDK_VERSION }}

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      shell: bash
      run: |
        source env/activate
        cmake -G Ninja \
        -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DCMAKE_BUILD_PARALLEL_LEVEL=4 \
        -DTTMLIR_ENABLE_RUNTIME=OFF \
        -DTTMLIR_ENABLE_RUNTIME_TESTS=OFF \
        -S ${{ github.workspace }}

    - name: Build
      shell: bash
      run: |
        source env/activate
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Lint
      shell: bash
      run: |
        source env/activate
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release -- clang-tidy

    - name: Run Test
      shell: bash
      run: |
        source env/activate
        export TTMLIR_TEST_WORKFLOW=nightly # turn on randomized mode for participating gtests
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release -- check-ttmlir

    - name: Build ttrt
      shell: bash
      run: |
        source env/activate
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-macos-latest
        path: build/test/report.xml

    - name: Show Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: build/test/report.xml
        check_name: macos-latest MLIR Tests
